### ISSUE TITLE
Hermit now supports sending to bech32 addresses

### ISSUE THREAD

**Issue by destrys** [unchained-capital/unchained-wallets#20]
`HermitSignTransaction` still returns an error message when attempting to generate a signature request for hermit if any of the outputs are bech32.

We have updated hermit to be able to send to bech32 addresses, so this error should be removed.

Looks like `outputsAreSupported` could just be removed:
https://github.com/unchained-capital/unchained-wallets/blob/master/src/hermit.js#L316

**Comment by jevidon** [comment]
Hello! The unchained-wallets library is transitioning to a new home, and as part of this move current issues will be closed and archived: https://github.com/caravan-bitcoin/caravan/issues
