### ISSUE TITLE
Support Hwi through BTCPay Vault (Trezor/KeepKey/Ledger/Coldcard, etc)

### ISSUE THREAD

**Issue by Kukks** [unchained-capital/unchained-wallets#23]
BTCPay has a cross platform desktop application that wraps a small UI and a webserver around the HWI project in order to interact with hardware wallets. The HWI direct integration is great as it does not rely on connecting to third party services (such as Trezor Connect) and abstracts them all to one common interface.

BTCPay Vault: https://github.com/btcpayserver/BTCPayServer.Vault
HWI: https://github.com/bitcoin-core/HWI/issues

**Comment by jevidon** [comment]
Hello! The unchained-wallets library is transitioning to a new home, and as part of this move current issues will be closed and archived. If you're still interested in your issue being addressed, please reopen it at the new location: https://github.com/caravan-bitcoin/caravan/issues
