### ISSUE TITLE
Ledger now shows "Unverified Inputs" on p2wsh post webusb

### ISSUE THREAD

**Issue by waldenraines** [unchained-capital/unchained-wallets#32]
I am now seeing this on the p2wsh tests in caravan:

![IMG_20200721_155249211](https://user-images.githubusercontent.com/4116405/88181677-371c7e00-cbfd-11ea-9c4d-2a05e3b2a6a6.jpg)

I also see this when authoring p2wsh transactions in caravan.

We should add this to the informational messages shown upon signing.

**Comment by jevidon** [comment]
The unchained-wallets library is transitioning to a new home, and as part of this move current issues will be closed and archived. You are welcome to reopen the issue there: https://github.com/caravan-bitcoin/caravan/issues
