### ISSUE TITLE
Capture invalid channel error and show relevant message

### ISSUE THREAD

**Issue by waldenraines** [unchained-capital/unchained-wallets#42]
We should capture this invalid channel error and show a message about reconnecting your ledger:  

```
{'component': 'XpubKeyExport', 'storeState': {'walletType': 'ledger'}, 'errorType': 'Device Xpub Export Error', 'message': 'Invalid channel', 'deviceError': 'Invalid channel'}
```

See https://support.ledger.com/hc/en-us/articles/360026371854-Invalid-channel

I'm not 100% sure how to cause this issue but we have seen people run into it and handling it would be good.

**Comment by jevidon** [comment]
Hello! The unchained-wallets library is transitioning to a new home, and as part of this move current issues will be closed and archived. This issue may be resolved now as part of other work, but if you believe it is still an issue you are welcome to reopen in the new repo: https://github.com/caravan-bitcoin/caravan/issues
